phonenummanage/urls.py
from django.contrib import admin
from django.urls import path
from web.views import account, admin, phone

urlpatterns = [
    path('',account.login),
    # path('admin/', admin.site.urls),
    path('login/', account.login),
    path('logout/', account.logout),
    path('img/code/', account.img_code),
    path('home/', account.home),

    path('admin/list/', admin.admin_list),
    path('admin/add/', admin.add_admin),
    path('admin/edit/<int:aid>/', admin.edit_admin),
    path('admin/delete/', admin.delete_admin),

    path('phone/list/', phone.phone_list),
    path('phone/add/', phone.add_phone),
    path('phone/edit/<int:pid>/', phone.edit_phone),
    path('phone/delete/', phone.delete_phone),
]

web/models.py
from django.db import models


class Department(models.Model):
    """部门表"""
    title = models.CharField(verbose_name='部门名称', max_length=16)

    def __str__(self):
        return self.title


class Admin(models.Model):
    """管理员表"""
    username = models.CharField(verbose_name='管理员姓名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    age = models.IntegerField(verbose_name='年龄', null=True, blank=True)
    gender = models.IntegerField(
        verbose_name='性别',
        choices=[(1, '男'),
                 (2, '女'),
                 ],
        default=1
    )
    depart_id = models.ForeignKey(verbose_name='部门', to='Department', on_delete=models.CASCADE)

    def __str__(self):
        return self.username


class Phone(models.Model):
    """靓号表"""
    mobile = models.CharField(verbose_name='手机号', max_length=11)
    price = models.PositiveIntegerField(verbose_name='价格', default=0)
    level = models.SmallIntegerField(
        verbose_name='级别',
        choices=[
            (1, '1级'),
            (2, '2级'),
            (3, '3级'),
        ],
        default=1
    )

    status_choices = (
        (1, '已使用'),
        (2, '未使用')
    )
    status = models.SmallIntegerField(
        verbose_name='状态',
        choices=status_choices,
        default=2
    )
    admin = models.ForeignKey(verbose_name='管理员', to='Admin', on_delete=models.CASCADE)

web/views/account.py
from io import BytesIO

from django import forms
from django.shortcuts import render, HttpResponse, redirect

from web import models
from utils.encrypt import md5
from utils.helper import check_code


class LoginForm(forms.Form):
    username = forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class": "form-control",
                                      "placeholder": "请输入用户名"})
    )
    password = forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class": "form-control",
                                          "placeholder": "请输入用户名"},
                                   render_value=True)
    )
    code = forms.CharField(
        label='验证码',
        widget=forms.TextInput(attrs={'class': "form-control",
                                      'placeholder': '请输入验证码', })

    )


def login(request):
    """ 用户登录 """
    if request.method == 'GET':
        form = LoginForm()
        return render(request, "login.html", {"form": form})
    form = LoginForm(data=request.POST)
    if not form.is_valid():
        return render(request, "login.html", {"form": form})
    # 1.判断验证码是否正确
    image_code = request.session.get("image_code")
    # 验证码失效
    if not image_code:
        form.add_error("code", "验证码过期")
        return render(request, "login.html", {"form": form})
    if image_code.upper() != form.cleaned_data["code"].upper():
        form.add_error("code", "验证码错误")
        return render(request, "login.html", {"form": form})
    # 2.验证码正确去数据库校验密码用户名
    username = form.cleaned_data["username"]
    password = form.cleaned_data["password"]  # md5 加密在与数据库比较
    encrypted_password = md5(password)
    admin_object = models.Admin.objects.filter(username=username, password=encrypted_password).first()
    if not admin_object:
        return render(request, "login.html", {"form": form, "error": "用户名或密码错误"})
    # 保存session，并七天免登录
    request.session["info"] = {"id": admin_object.id, "username": admin_object.username}
    request.session.set_expiry(60 * 60 * 24 * 7)
    return redirect('/home/')


def img_code(request):
    """ 验证码功能 """
    # 1.生成图片
    img_obj, code_str = check_code()

    # 2.把图片写入内存，从内存中读取并返回
    stream = BytesIO()
    img_obj.save(stream, 'png')

    # 3.将图片内容写进session中 + 60s
    request.session["image_code"] = code_str
    request.session.set_expiry(60)

    return HttpResponse(stream.getvalue())


def logout(request):
    """ 注销功能 """
    request.session.clear()
    return redirect("/login/")


def home(request):
    """ 进入主页面"""
    return render(request, "home.html")

web/views/admin.py
from django import forms
from django.http import JsonResponse
from django.shortcuts import render, redirect

from web import models
from utils.encrypt import md5


def admin_list(request):
    """ 管理员列表 """

    # queryst : [obj,obj,...]
    queryset = models.Admin.objects.all().order_by("id")

    return render(request, "admin_list.html", {"queryset": queryset})


class AdminModelForm(forms.ModelForm):
    class Meta:
        model = models.Admin
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 自定义操作
        for name, filed_object in self.fields.items():
            filed_object.widget.attrs = {"class": "form-control"}


def add_admin(request):
    if request.method == "GET":
        form = AdminModelForm()
        return render(request, "admin_form.html", {"form": form})

    form = AdminModelForm(data=request.POST)
    if not form.is_valid():
        return render(request, "admin_form.html", {"form": form})

    # 密码更新为md5加密
    form.instance.password = md5(form.instance.password)
    form.save()
    return redirect('/admin/list/')


class AdminEditModelForm(forms.ModelForm):
    class Meta:
        model = models.Admin
        fields = ["username", "age", "gender", "depart_id"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 自定义操作
        for name, filed_object in self.fields.items():
            filed_object.widget.attrs = {"class": "form-control"}


def edit_admin(request, aid):
    admin_object = models.Admin.objects.filter(id=aid).first()

    if request.method == 'GET':
        form = AdminEditModelForm(instance=admin_object)
        return render(request, 'admin_form.html', {"form": form})

    form = AdminEditModelForm(instance=admin_object, data=request.POST)
    if not form.is_valid():
        return render(request, "admin_form.html", {"form": form})
    # 更新
    form.save()
    return redirect('/admin/list/')


def delete_admin(request):
    aid = request.GET.get('aid')
    models.Admin.objects.filter(id=aid).delete()

    # 内部进行序列化
    return JsonResponse({"status": True})

web/views/phone.py
from django import forms
from django.http import JsonResponse
from django.shortcuts import render, redirect

from web import models


def phone_list(request):
    """ 手机号查询 """
    queryset = models.Phone.objects.all().order_by("id")
    return render(request, "phone_list.html", {"queryset": queryset})


class PhoneModelForm(forms.ModelForm):
    class Meta:
        model = models.Phone
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 自定义操作
        for name, filed_object in self.fields.items():
            filed_object.widget.attrs = {"class": "form-control"}


def add_phone(request):
    """ 添加手机号 """
    if request.method == 'GET':
        form = PhoneModelForm()
        return render(request, "phone_form.html", {"form": form})

    form = PhoneModelForm(data=request.POST)
    if not form.is_valid():
        return render(request, "phone_form.html", {"form": form})
    form.save()
    return redirect('/phone/list/')


def edit_phone(request, pid):
    """ 修改手机号 """
    phone_object = models.Phone.objects.filter(id=pid).first()

    if request.method == "GET":
        form = PhoneModelForm(instance=phone_object)
        return render(request, "phone_form.html", {"form": form})

    form = PhoneModelForm(instance=phone_object, data=request.POST)
    if not form.is_valid():
        return render(request, "phone_form.html", {"form": form})
    form.save()
    return redirect("/phone/list/")


def delete_phone(request):
    """ 删除手机号 """
    pid = request.GET.get('pid')
    models.Phone.objects.filter(id=pid).delete()

    # 内部进行序列化
    return JsonResponse({"status": True})

web/templates/admin_form.html
{% extends 'layout.html' %}
{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            表单操作
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">保 存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

web/templates/admin_list.html
{% extends 'layout.html' %}
{% block content %}

    <div style="margin-top: 10px;margin-bottom: 10px;">
        <a class="btn btn-success" href="/admin/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建用户
        </a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>用户名</th>
            <th>性别</th>
            <th>年龄</th>
            <th>部门</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in queryset %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.username }}</td>
                <td>{{ row.age }}</td>
                <td>{{ row.get_gender_display }}</td>
                <td>{{ row.depart_id.title }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/admin/edit/{{ row.id }}/">
                        编辑
                    </a>
                    <input type="button" value="删 除" class="btn btn-danger btn-xs"
                           onclick="deleteAction({{ row.id }});">
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4>是否确定删除？</h4>
                <p>删除后，与之关联的所有相关的数据都会被删除掉，确认是否继续？</p>
                <p>
                    <button type="button" class="btn btn-danger" onclick="confirmDelete()">确 认</button>
                    <button type="button" class="btn btn-default" onclick="cancelDelete()">取 消</button>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        DELETE_ID = 0;

        function deleteAction(id) {
            {#当前要删除的id#}
            DELETE_ID = id;
            $('#myModal').modal("show")
        }

        function confirmDelete(id) {
            {#像后端发送删除请求#}
            {#页面刷新#}
            // xxx/admin/delete/?aid=DELETE_ID
            $.ajax({
                url: "/admin/delete/",
                type: "GET",
                data: {
                    aid: DELETE_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        // 刷新页面
                        location.reload()
                    } else {
                        alert(res.error);
                    }
                }
            })
        }

        function cancelDelete() {
            DELETE_ID = 0;
            $('#myModal').modal("hide");
        }
    </script>
{% endblock %}

web/templates/home.html
{% extends 'layout.html' %}
{% block content %}
    <h3>欢迎{{ request.info_dict.username }}登录靓号管理系统</h3>
{% endblock %}

web/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
    {% block css %}{% endblock %}
</head>
<body>

<nav class="navbar navbar-default" style="border-radius: 0;">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">靓号管理系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/admin/list/">用户管理</a></li>
                <li><a href="/phone/list/">号码管理</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.info_dict.username }}</a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li><a href="#">修改密码</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery3.6.0.js' %}"></script>
<script src="{% static 'plugins/bootstrap-3.4.1/js/bootstrap.min.js' %}"></script>
{% block js %}{% endblock %}
</body>
</html>

web/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.min.css' %}">
</head>
<style>
    .login-box {
        width: 400px;
        margin: 220px auto 0;
        border: 1px solid #ffff00;
        padding: 20px;
    }

    .login-box h1 {
        text-align: center;
    }
</style>
<body>
<div class="login-box">
    <h1>登录</h1>
    <form method="post" action="/login/" novalidate>
        {% csrf_token %}
        <div class="form-group">
            <label>{{ form.username.label }}</label>
            {{ form.username }}
            <span style="color: red">{{ form.username.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>{{ form.password.label }}</label>
            {{ form.password }}
            <span style="color: red">{{ form.password.errors.0 }}</span>
        </div>
        <div class="form-group">
            <label>{{ form.code.label }}</label>
            <div class="row">
                <div class="col-xs-6">
                    {{ form.code }}
                </div>
                <div class="col-xs-6">
                    <img src="/img/code/" id="CodeImg" style="cursor: pointer">
                </div>
            </div>
            <span style="color: red">{{ form.code.errors.0 }}</span>
        </div>
        <button type="submit" class="btn btn-primary">提 交</button>
        <span style="color: red">{{ error }}</span>
    </form>
</div>
<script src="{% static 'js/jquery3.6.0.js' %}"></script>
<script>
    $(function () {
        $("#CodeImg").click(function () {
            {#获取到当前的图片url，再赋新url改变图片#}
            var url = $(this).attr('src');
            $(this).attr('src', url + "?");
        });
    })
</script>
</body>
</html>

web/templates/phone_form.html
{% extends 'layout.html' %}
{% block content %}

    <div class="panel panel-default">
        <div class="panel-heading">
            <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span>
            表单操作
        </div>
        <div class="panel-body">
            <form class="form-horizontal" method="post" novalidate>
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        <label class="col-sm-2 control-label">{{ field.label }}</label>
                        <div class="col-sm-10">
                            {{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <button type="submit" class="btn btn-primary">保 存</button>
                    </div>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

web/templates/phone_list.html
{% extends 'layout.html' %}
{% block content %}
    <div style="margin-top: 10px;margin-bottom: 10px;">
        <a class="btn btn-success" href="/phone/add/">
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
            新建手机号
        </a>
    </div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>ID</th>
            <th>手机号</th>
            <th>价格</th>
            <th>级别</th>
            <th>状态</th>
            <th>管理员</th>
            <th>操作</th>
        </tr>
        </thead>
        <tbody>
        {% for row in queryset %}
            <tr>
                <td>{{ row.id }}</td>
                <td>{{ row.mobile }}</td>
                <td>{{ row.price }}</td>
                <td>{{ row.get_level_display }}</td>
                <td>{{ row.get_status_display }}</td>
                <td>{{ row.admin.username }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/phone/edit/{{ row.id }}/">
                        编辑
                    </a>
                    <input type="button" value="删 除" class="btn btn-danger btn-xs"
                           onclick="deleteAction({{ row.id }});">
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">×</span></button>
                <h4>是否确定删除？</h4>
                <p>删除后，与之关联的所有相关的数据都会被删除掉，确认是否继续？</p>
                <p>
                    <button type="button" class="btn btn-danger" onclick="confirmDelete()">确 认</button>
                    <button type="button" class="btn btn-default" onclick="cancelDelete()">取 消</button>
                </p>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        DELETE_ID = 0;

        function deleteAction(id) {
            {#当前要删除的id#}
            DELETE_ID = id;
            $('#myModal').modal("show")
        }

        function confirmDelete(id) {
            {#像后端发送删除请求#}
            {#页面刷新#}
            // xxx/admin/delete/?pid=DELETE_ID
            $.ajax({
                url: "/phone/delete/",
                type: "GET",
                data: {
                    pid: DELETE_ID
                },
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        // 刷新页面
                        location.reload()
                    } else {
                        alert(res.error);
                    }
                }
            })
        }

        function cancelDelete() {
            DELETE_ID = 0;
            $('#myModal').modal("hide");
        }
    </script>
{% endblock %}